name: docker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check:
    name: check if new version of minikube is available
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.check.outputs.latest_tag }}
      latest_version: ${{ steps.latest-version.outputs.tag }}
    permissions:
      contents: read
      packages: read
    steps:
      - name: get existing minikube tags
        id: check
        shell: bash
        run: |
          TAGS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/Gridness/minikube/tags/list | jq -r '.tags[]')
          LATEST_TAG=$(echo "$TAGS" | sort -V | tail -n1)
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: check if new minikube version is available
        id: latest-version
        uses: oprypin/find-latest-tag@v1
        with:
          repository: kubernetes/minikube
          releases-only: true

  build:
    name: build minikube image
    needs: check
    if: ${{ needs.check.outputs.latest_version != needs.check.outputs.latest_tag }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0

      - name: extract docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/minikube
          tags: |
            type=raw,value=latest
            type=raw,value=${{ needs.check.outputs.latest_version }}

      - name: show metadata
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            VERSION=${{ needs.check.outputs.latest_version }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

  release:
    name: publish new version release
    needs: [check, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5.0.0

      - name: publish new release
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ needs.check.outputs.latest_version }}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${{ needs.check.outputs.latest_version }}" \
            --generate-notes
